services:
  database:
    image: postgres:latest
    environment:
      - 'POSTGRES_DB=customers-database'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
  service:
    image: mspr4-2025/customers-service
    ports:
      - '8080:8080'
    depends_on:
      - database