services:
  customers-database:
    image: postgres:latest
    ports:
      - '5434:5432'
    env_file:
      - .env
    environment:
      - 'POSTGRES_DB=${DATABASE_NAME}'
      - 'POSTGRES_USER=${DATABASE_USER}'
      - 'POSTGRES_PASSWORD=${DATABASE_PASS}'
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
    - /tmp/rabbitmq-data:/var/lib/rabbitmq

  customers-service:
    image: ghcr.io/mspr4-2025/customers-service
    ports:
      - '8082:8080'
    env_file:
      - .env
    environment:
      DATABASE_HOST: customers-database
      DATABASE_PORT: 5432
      spring.rabbitmq.host: rabbitmq
      spring.rabbitmq.port: 5672
      spring.rabbitmq.username: guest
      spring.rabbitmq.password: guest
      spring.rabbitmq.virtual-host: /
    depends_on:
      - customers-database
      - rabbitmq

  