name: Test

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - build.gradle
      - settings.gradle
      - .github/workflows/test.yml
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - run: chmod +x ./gradlew

      - name: Test
        run: ./gradlew test --tests "*"

      - name: Test Report
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}
        with:
          name: Tests
          path: build/test-results/test/*.xml
          reporter: java-junit
